# Generated by Django 4.0.2 on 2022-07-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskData', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
