# Generated by Django 4.0.2 on 2022-07-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskData', '0003_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(max_length=20)),
                ('username', models.TextField(max_length=50)),
                ('email_id', models.TextField(max_length=50)),
                ('forget_token', models.TextField(max_length=1000)),
            ],
        ),
    ]
